TicTacToe/Areas/Account/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicTacToe.Services;

namespace TicTacToe.Areas.Account.Controllers
{
    [Area("Account")]
    public class HomeController : Controller
    {
        private readonly IUserService _userService;

        public HomeController (IUserService userService)
        {
            _userService = userService;
        }

        public async  Task<IActionResult> Index()
        {
            var email = HttpContext.Session.GetString("email");
            var user = await _userService.GetUserByEmail(email);
            return View(user);
        }
    }
}

TicTacToe/Controllers/LeaderboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicTacToe.Services;

namespace TicTacToe.Controllers
{
    public class LeaderboardController : Controller
    {
        private readonly IUserService _userService;

        public LeaderboardController (IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userService.GetTopUsers(10);
            return View(users);
        }
    }
}

TicTacToe/Views/Shared/_Account.cshtml
@model TicTacToe.Models.AccountModel

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="glypicon glyphicon-user"></span>
        <strong>@Model.DisplayName</strong>
        <span class="glyphicon glyphicon-chevron-down"></span>
    </a>
    <ul class="dropdown-menu" id="connected-dp">
        <li>
            <div class="navbar-login">
                <div class="row">
                    <div class="col-lg-4">
                        <p class="text-center">
                            <Gravatar email="@Model.Email">
                            </Gravatar>
                        </p>
                    </div>

                    <div class="col-lg-8">
                        <p class="text-left">
                            <strong>@Model.DisplayName </strong>
                        </p>
                        <p class="text-left small">
                            <a asp-action="Index" asp-controller="Account">@Model.Email</a>
                        </p>
                    </div>
                </div>
            </div>
        </li>
        <li class="divider"></li>
        <li>
            <div class="navbar-login navbar-login-session">
                <div class="row">
                    <div class="col-lg-12">
                        <p>
                            <a href="#" class="btn btn-danager btn-block">Log off</a>
                            <a class="btn btn-default btn-block" asp-action="Index"
                               asp-controller="Account">View Details</a>
                        </p>
                    </div>
                </div>
            </div>
        </li>
    </ul>
</li>

TicTacToe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <title>@ViewData["Title"] - TicTacToe</title>
        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-testproperty="position"
                  asp-fallback-test-value="absolute" crossorigin="anonymous"
                  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        </environment>
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicTacToe</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <partial name="_Menu" />
                </div>
            </nav>
        </header>

        <div class="container body-content">
            <main role="main" class="pb-3">
                @RenderSection("Desktop", required: false)
                @if(IsSectionDefined("Mobile")) { IgnoreSection("Mobile"); }
                @RenderBody()
            </main>
            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2019 - TicTacToe -
                    <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)

        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
        </environment>
       


    </body>
</html>

TicTacToe/Views/Shared/_LayoutEmail.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial=scale=1.0" />
        <title>@ViewData["Title"] - TicTacToe</title>
        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstarp.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet"
                  href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only"
                  asp-fallback-test-property="position" />
            <link rel="stylesheet" href="~/css/site.min.css"
                  asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>
                    &copy; 2021 - TicTacToe
                </p>
            </footer>
        </div>
        <environment include="Development">
            <script src="~/lib/jquery/dist/jquesy.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        @RenderSection("Scripts", required: false)
    </body>
</html>

TicTacToe/Views/Shared/_LayoutMobile.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <title>@ViewData["Title"] - TicTacToe</title>
        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-testproperty="position"
                  asp-fallback-test-value="absolute" crossorigin="anonymous"
                  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        </environment>
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicTacToe</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <partial name="_Menu" />
                    
                </div>
            </nav>
        </header>

        <div class="container body-content">
            <main role="main" class="pb-3">
                @RenderSection("Mobile", required: false)
                @if(IsSectionDefined("Desktop")) { IgnoreSection("Desktop"); }
                @RenderBody()
            </main>
            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2019 - TicTacToe -
                    <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)

        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
        </environment>
      


    </body>
</html>

TicTacToe/Views/Shared/_Menu.cshtml
@using Microsoft.AspNetCore.Http;
@{ 
    var email = Context.Session.GetString("email");
    var displayName = Context.Session.GetString("displayName");
}

<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-rowreverse">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
               asp-action="Index">
                Home
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
               asp-action="Privacy">
                Privacy
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link text-dark" asp-area=""
               asp-controller="Leaderboard" asp-action="Index">Leaderboard</a>
        </li>

        <li>
            @if (!string.IsNullOrEmpty(email))
            {
                Html.RenderPartial("_Account", new TicTacToe.Models.AccountModel
                {
                    Email = email,
                    DisplayName = displayName
                });
            }
        </li>

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Settings
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu multi-level">
                <li class="dropdown-submenu">
                    <a class="dropdown-toggle" data-toggle="dropdown"
                       href="#">
                        Select your language (@ViewBag.Language)
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li @(ViewBag.Language == "EN" ? "active" : "")>
                            <a asp-controller="Home" asp-action="SetCulture"
                               asp-route-culture="EN">English</a>
                        </li>
                        <li @(ViewBag.Language == "FR" ? "active" : "")>
                            <a asp-controller="Home" asp-action="SetCulture"
                               asp-route-culture="FR">French</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>